version: '3.8'

services:
  flask:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"  
    depends_on:
      - mongodb 

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  
      MONGO_INITDB_ROOT_PASSWORD: password 

